# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job01:
    name: run (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]  # , "macos-latest", "windows-latest"]
        python-version: ["3.8"]
    steps:
      - uses: conda-incubator/setup-miniconda@v1.7.0
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Create environment
        run: conda env create -q -f iblenv.yaml

      - name: Checkout ibllib develop
        uses: actions/checkout@v2.3.4
        with:
          repository: int-brain-lab/ibllib
      - name: Checkout iblapps develop
        uses: actions/checkout@v2.3.4
        with:
          repository: int-brain-lab/iblapps
      - name: Checkout IBL-pipeline master
        uses: actions/checkout@v2.3.4
        with:
          repository: int-brain-lab/IBL-pipeline
      - name: Checkout analysis master
        uses: actions/checkout@v2.3.4
        with:
          repository: int-brain-lab/analysis
      - name: Checkout iblenv master
        uses: actions/checkout@v2.3.4
        with:
          repository: int-brain-lab/iblenv
      - name: Checkout phylib master
        uses: actions/checkout@v2.3.4
        with:
          repository: cortex-lab/phylib
      - name: Checkout phy master
        uses: actions/checkout@v2.3.4
        with:
          repository: cortex-lab/phy
      - name: Activate environment
        run: conda activate iblenv
      - name: Set mode to develop  ibllib
        run: conda develop $GITHUB_WORKSPACE/ibllib
      - name: Set mode to develop  iblapps
        run: conda develop $GITHUB_WORKSPACE/iblapps
      - name: Set mode to develop  analysis
        run: conda develop $GITHUB_WORKSPACE/analysis
      - name: Set mode to develop  IBL-pipeline
        run: conda develop $GITHUB_WORKSPACE/IBL-pipeline
      - name: Set mode to develop  phy
        run: conda develop $GITHUB_WORKSPACE/phy
      - run: conda develop $GITHUB_WORKSPACE/phylib
