# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  install:
    name: build (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.8"]
    steps:
      - name: Clone iblenv repo
        uses: actions/checkout@v2

      # - uses: conda-incubator/setup-miniconda@v1.7.0
      #   with:
      #     activate-environment: iblenv
      #     environment-file: iblenv.yml

      - name: Clone ibllib
        uses: actions/checkout@v2.3.4
        with:
          repository: int-brain-lab/ibllib
          path: ibllib

      - name: Clone iblapps
        uses: actions/checkout@v2.3.4
        with:
          repository: int-brain-lab/iblapps
          path: iblapps

      - name: Clone IBL-pipeline
        uses: actions/checkout@v2.3.4
        with:
          repository: int-brain-lab/IBL-pipeline
          path: IBL-pipeline

      - name: Clone iblapps
        uses: actions/checkout@v2.3.4
        with:
          repository: int-brain-lab/analysis
          path: analysis

      - name: Clone phylib
        uses: actions/checkout@v2.3.4
        with:
          repository: cortex-lab/phylib
          path: phylib

      - name: Clone phy
        uses: actions/checkout@v2.3.4
        with:
          repository: cortex-lab/phy
          path: phy

      # ----------------------------------------
      - name: Install Miniconda, environment and activate
        shell: bash
        run: |
          if [[ "${{ runner.os }}" = "Linux" ]]; then
            MINICONDA_FILENAME=Miniconda3-latest-Linux-x86_64.sh
            curl -o $MINICONDA_FILENAME "https://repo.continuum.io/miniconda/$MINICONDA_FILENAME"
            bash ${MINICONDA_FILENAME} -b -f -p $HOME/miniconda3
          elif [[ "${{ runner.os }}" = "macOS" ]]; then
            MINICONDA_FILENAME=Miniconda3-latest-MacOSX-x86_64.sh
            curl -o $MINICONDA_FILENAME "https://repo.continuum.io/miniconda/$MINICONDA_FILENAME"
            bash ${MINICONDA_FILENAME} -b -f -p $HOME/miniconda3
          elif [[ "${{ runner.os }}" = "Windows" ]]; then
            MINICONDA_FILENAME=Miniconda3-latest-Windows-x86_64.exe
            curl -o $MINICONDA_FILENAME "https://repo.continuum.io/miniconda/$MINICONDA_FILENAME"
            ./Miniconda3-latest-Windows-x86_64.exe //InstallationType=JustMe //RegisterPython=0 //S
          fi

      # - name: Init all conda shells
      #   run: $CONDA/bin/conda init --all

      - name: Create environment
        shell: bash
        run: $CONDA/bin/conda env create -q -f iblenv.yaml

      - name: Activate iblenv
        shell: bash
        run: $CONDA/bin/activate iblenv

      - name: Install IBL repos
        shell: bash
        run: |
          pip3 install -e ibllib
          pip3 install -e iblapps
          pip3 install -e analysis
          pip3 install -e IBL-pipeline
          pip3 install -e phy
          pip3 install -e phylib
