# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job01:
    name: build (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 6
      matrix:
        os: ["ubuntu-latest"]  # , "macos-latest", "windows-latest"]
        python-version: ["3.8"]
    steps:
      - uses: actions/checkout@v2

      - run: pwd
      # - run: git
      - run: ls
      - run: ls ../
      - run: ls ../../
      - run : ls $GITHUB_WORKSPACE

      - name: Create environment
        run: $CONDA/bin/conda env create -q -f iblenv.yaml

      - name: Init all conda shells
        run: |
          $CONDA/bin/conda init --all

      - name: Activate iblenv
        run: $CONDA/bin/activate iblenv

      - name: Clone ibllib
        uses: actions/checkout@v2.3.4
        with:
          repository: int-brain-lab/ibllib

      - name: Clone iblapps
        uses: actions/checkout@v2.3.4
        with:
          repository: int-brain-lab/iblapps

      - name: Clone IBL-pipeline
        uses: actions/checkout@v2.3.4
        with:
          repository: int-brain-lab/IBL-pipeline

      - name: Clone iblapps
        uses: actions/checkout@v2.3.4
        with:
          repository: int-brain-lab/analysis

      - name: Clone phylib
        uses: actions/checkout@v2.3.4
        with:
          repository: cortex-lab/phylib

      - name: Clone phy
        uses: actions/checkout@v2.3.4
        with:
          repository: cortex-lab/phy

      - name: Install IBL repos
        run: |
          pip install -e $GITHUB_WORKSPACE/ibllib/
          pip install -e $GITHUB_WORKSPACE/iblapps/
          pip install -e $GITHUB_WORKSPACE/analysis/
          pip install -e $GITHUB_WORKSPACE/IBL-pipeline/
          pip install -e $GITHUB_WORKSPACE/phy/
          pip install -e $GITHUB_WORKSPACE/phylib/
