# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  install:
    name: build (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 6
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.8"]
    steps:
      - name: Clone iblenv repo
        uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v1
        with:
          activate-environment: iblenv
          environment-file: iblenv.yml

      - name: Clone ibllib
        uses: actions/checkout@v2.3.4
        with:
          repository: int-brain-lab/ibllib
          path: ibllib

      - name: Clone iblapps
        uses: actions/checkout@v2.3.4
        with:
          repository: int-brain-lab/iblapps
          path: iblapps

      - name: Clone IBL-pipeline
        uses: actions/checkout@v2.3.4
        with:
          repository: int-brain-lab/IBL-pipeline
          path: IBL-pipeline

      - name: Clone iblapps
        uses: actions/checkout@v2.3.4
        with:
          repository: int-brain-lab/analysis
          path: analysis

      - name: Clone phylib
        uses: actions/checkout@v2.3.4
        with:
          repository: cortex-lab/phylib
          path: phylib

      - name: Clone phy
        uses: actions/checkout@v2.3.4
        with:
          repository: cortex-lab/phy
          path: phy

      # ----------------------------------------
      # - name: Create environment (bash-conda)
      #   shell: bash -l {0}
      #   run: conda env create -q -f iblenv.yaml

      # - name: Create environment (bash)
      #   shell: bash -l {0}
      #   run: $CONDA/bin/conda env create -q -f iblenv.yaml

      # - name: Create environment (PS)
      #   shell: powershell
      #   run: $CONDA\bin\conda env create -q -f iblenv.yaml

      # - name: Create environment (sh)
      #   shell: sh -l {0}
      #   run: $CONDA/bin/conda env create -q -f iblenv.yaml

      # - name: Init all conda shells
      #   run: |
      #     $CONDA/bin/conda init --all

      # - name: Activate iblenv
      #   run: $CONDA/bin/activate iblenv

      - name: Install IBL repos
        run: |
          conda develop ibllib
          conda develop iblapps
          conda develop analysis
          conda develop IBL-pipeline
          conda develop phy
          conda develop phylib
