# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job01:
    name: run (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]  # , "macos-latest", "windows-latest"]
        python-version: ["3.8"]
    steps:
      - uses: actions/checkout@v2

      - run: pwd
      # - run: git
      - run: ls
      - run: ls ../
      - run: ls ../../
      - run : ls $GITHUB_WORKSPACE

      - name: Create environment
        run: $CONDA/bin/conda env create -q -f iblenv.yaml

      - name: Init all conda shells
        run: |
          $CONDA/bin/conda init --all

      - run: $CONDA/bin/activate iblenv

      - uses: actions/checkout@v2.3.4
        with:
          repository: int-brain-lab/ibllib
      - uses: actions/checkout@v2.3.4
        with:
          repository: int-brain-lab/iblapps
      - uses: actions/checkout@v2.3.4
        with:
          repository: int-brain-lab/IBL-pipeline
      - uses: actions/checkout@v2.3.4
        with:
          repository: int-brain-lab/analysis
      - uses: actions/checkout@v2.3.4
        with:
          repository: int-brain-lab/iblenv
      - uses: actions/checkout@v2.3.4
        with:
          repository: cortex-lab/phylib
      - uses: actions/checkout@v2.3.4
        with:
          repository: cortex-lab/phy

      - name: Set all c/o repos to conda develop
        run: |
          $CONDA/bin/conda develop $GITHUB_WORKSPACE/ibllib
          $CONDA/bin/conda develop $GITHUB_WORKSPACE/iblapps
          $CONDA/bin/conda develop $GITHUB_WORKSPACE/analysis
          $CONDA/bin/conda develop $GITHUB_WORKSPACE/IBL-pipeline
          $CONDA/bin/conda develop $GITHUB_WORKSPACE/phy
          $CONDA/bin/conda develop $GITHUB_WORKSPACE/phylib
